### ISSUE TITLE
Setup as a Declarative Gradle home repo

### ISSUE THREAD

**Issue by oleg-nenashev** [gradle/declarative-gradle#17]
After renaming the repository, it would be nice to set it up as a Declarative Gradle home repo where we can keep the dynamic content, including but not limited to:

- Prototypes, as of now
- Overview, Manifesto
- Public tickets and milestones for the Declarative Gradle project before GA
- Documentation for early adopters, open to quick contributions and feedback
- Issue tracker for community evaluation

**Comment by elect86** [comment]
> Documentation for early adopters, open to quick contributions and feedback

Sorry Oleg, but where can I find this documentation for early adopters you mention?
