### ISSUE TITLE
🚀 Release first Alpha binaries for Declarative Gradle plugins

### ISSUE THREAD

**Issue by oleg-nenashev** [gradle/declarative-gradle#39]
We want to publish an alpha release of the plugins currently used in prototypes to enable initial evaluation. These releases will not guarantee any compatibility and may be removed in the future.

## Scope

- [x] Bits are released to destination repositories, e.g., Gradle Build Tool nightly Builds or Gradle Plugin Portal
- [x] There is some documentation on how to get the bits
- [x] Demos are updated to use this release
- [x] There are underlying release pipelines, preferable designed for fast ad-hoc alpha releases
- [x] There is changelog, e.g. on GitHub Releases in this repository

**Comment by octylFractal** [comment]
Publishing work is in #37

**Comment by oleg-nenashev** [comment]
All was done in the July EAP
